### ISSUE TITLE
Cannot build when importing component

### ISSUE THREAD

**Issue by hornet-9** [youseedk/dna-react#4]
When using `import { Button } from '@youseedk/dna-react';` we get a build error, saying that the @ in this statement is not recognised. Build output:

![image](https://user-images.githubusercontent.com/11543018/61054280-6e9ffa00-a3ef-11e9-830e-9b8fa69c38d9.png)

**Comment by havgry** [comment]
Seems like dna-react is not playing nice with the YouSee gulp and browserify setup. I sort of just assumed a setup where css imports in js files were transformed but eh. I'll look into it :)

Thanks for the feedback 👍
